In [1]:
import numpy as np


In [4]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [7]:
np.zeros((5,5))
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [12]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [24]:
np.random.randint(0,100,(5,5))

array([[16, 81, 45, 76, 20],
       [59, 57, 94, 91, 32],
       [24, 37, 26, 55, 96],
       [73, 21, 27,  5, 36],
       [84, 40, 96, 53, 70]])

In [25]:
arr = np.arange(35)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34])

In [44]:
arr = np.random.randint(0,100,(5,5))
print(arr)

[[66 73 89 73 95]
 [99 47 78 84  3]
 [85 83 18 63 97]
 [ 3 62 32 86 68]
 [57 56 15 69 96]]


In [45]:
arr = arr.reshape(25)

In [48]:
arr[5:15]= 15
arr

array([66, 73, 89, 73, 95, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,  3, 62,
       32, 86, 68, 57, 56, 15, 69, 96])

In [59]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
print(arr[arr>5])

[ 6  7  8  9 10]


In [69]:
arr = arr[arr>5]

In [71]:
arr

array([ 6,  7,  8,  9, 10])

In [5]:
np.random.rand(10)

array([0.08541434, 0.08635306, 0.16387836, 0.70995194, 0.71915272,
       0.71053943, 0.22522163, 0.53915489, 0.67618978, 0.0769416 ])

In [9]:
arr = np.arange(100)
arr= arr.reshape(10,10)

In [24]:
arr.max(axis=1)

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [22]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [9]:
a = np.random.rand(100)

In [10]:
a


array([0.69843896, 0.21677491, 0.75888774, 0.81316807, 0.64888003,
       0.04941504, 0.18976315, 0.16567017, 0.15976494, 0.56724155,
       0.43508156, 0.36106046, 0.18649189, 0.07158452, 0.98332054,
       0.0257519 , 0.83998501, 0.31019778, 0.55684377, 0.25703201,
       0.19417497, 0.46037709, 0.17091297, 0.10403124, 0.08465195,
       0.65188561, 0.93651666, 0.87025224, 0.88964317, 0.63503359,
       0.84271239, 0.41913465, 0.22717392, 0.98696124, 0.37299642,
       0.60739041, 0.70101575, 0.31580676, 0.78461379, 0.29005693,
       0.65961187, 0.32738295, 0.00604605, 0.56349537, 0.52739683,
       0.14253053, 0.86514934, 0.9847877 , 0.99726733, 0.08139813,
       0.85294823, 0.73391509, 0.27945245, 0.72094093, 0.21414832,
       0.07092693, 0.08950082, 0.61621676, 0.41319518, 0.85538686,
       0.23212225, 0.96675048, 0.27426826, 0.49099632, 0.79556547,
       0.68635271, 0.35666636, 0.3926647 , 0.52890144, 0.63612076,
       0.3971163 , 0.06487185, 0.46367821, 0.85040988, 0.52419